[Certora] Handle overflows
morpho-org/morpho-token pull request #105
Opened 2024-12-16 08:44 UTC by colin-morpho

Replace absurd revert conditions with safe requirements that have been proven.
Fixes a very small typo in the `certora/README.md`.

2024-12-16 08:58 UTC, MathisGD submitted a review, later dismissed

2024-12-16 11:21 UTC, QGarchery requested changes
Looks great, but it seems like there are more of the same to do in `MintBurn` specification. For example:
https://github.com/morpho-org/morpho-token/blob/2ebbdff19540c913d270724512e46c042716cb86/certora/specs/MintBurnEthereum.spec#L80

2024-12-16 12:13 UTC, colin-morpho commented
> I think it's even possible to actually require the invariants themselves.

Actually it isn't because the invriants require the munging setup which introduce new possible owerflows related to the zero virtual voting power. 

>  toVotingPowerBefore + amount > max_uint256; 

I think this is a legitimate reason to revert, isn't it?

2024-12-16 14:24 UTC, colin-morpho commented
> A couple more to fix :

@QGarchery, I haven't managed to get these ones do not go through because of the same reason as :

> Actually it isn't because the invriants require the munging setup which introduce new possible owerflows related to the zero virtual voting power.


In particular, when votes are delegated to zero, `burn` subtracts the `amount` from the `zeroVirtualVotingPower` causing a revert that is caught by `fromVotingPowerBefore < amount` .

2024-12-16 14:59 UTC, QGarchery commented
> In particular, when votes are delegated to zero, burn subtracts the amount from the zeroVirtualVotingPower causing a revert that is caught by fromVotingPowerBefore < amount

Good point, but I think we can still frame it in terms of a "safe require". Here the invariant that we would want is that the balance of the sender is less that `_zeroVirtualVotingPower` in case where the sender delegates to 0

2024-12-16 15:18 UTC, colin-morpho commented
> Good point, but I think we can still frame it in terms of a "safe require". Here the invariant that we would want is that the balance of the sender is less that _zeroVirtualVotingPower in case where the sender delegates to 0

Just requiring the `delegatee(from) => fromBalanceBefore <= _zeroVirtualVotingPower`, isn't enough (see [this](https://prover.certora.com/output/129828/604bc6fda9544db0b77733212c144d49?anonymousKey=7d4d5a751e0259c0cb3e74d54a9591253db6f3b5) run), it looks like the prover isn't able to figure out that `amount <= fromBalanceBefore <= fromVotingPowerBefore`.

2025-01-14 11:45 UTC, QGarchery commented on certora/specs/ERC20.spec
> +    require holderBalanceBefore <= holderVotingPowerBefore;
See https://github.com/morpho-org/morpho-token/issues/107

2025-01-14 11:45 UTC, QGarchery commented on certora/specs/ERC20.spec
> +    require holderBalanceBefore <= holderVotingPowerBefore;
See https://github.com/morpho-org/morpho-token/issues/107

2025-01-16 08:47 UTC, QGarchery requested changes

2025-01-16 08:47 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    // Safe require as implementation woud revert.
Which implementation ? This is not as other rules, this one is to be used as an invariant. This means that you can require what you want, it will just have to be added in the premisses. For example, if you have the following rule:
```
require A;
require B;
assert C;
```
then later on you will be able to have the following "safe require":
`require A => B => C;`

2025-01-16 08:47 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    // Safe rquire as zero address can't initiate transactions.
```suggestion
    // Safe require as zero address can't initiate transactions.
```

2025-01-16 08:47 UTC, QGarchery commented on certora/specs/RevertsERC20.spec
> +    require delegatee(to) != delegatee(e.msg.sender) => recipientVotingPowerBefore + amount <= totalSupply();
How does it follow from those rules/invariants ? The rule `updatedDelegatedVPLTEqTotalSupply` requires `amount <= balanceOfSenderBefore` and `e.msg.sender != 0`

2025-01-16 08:47 UTC, QGarchery commented on certora/specs/RevertsERC20.spec
> +    // Safe require that follows from sumOfTwoDelegatedVPLTEqTotalVP() and totalSupplyIsSumOfVirtualVotingPower() and rule updatedDelegatedVPLTEqTotalSupply
Same

2025-01-16 08:47 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
It's not sound to do that in rules that you want to use as an invariant. For example, if `delegate` always reverted, then you would be able to prove anything in the else branch, and then you would use it later which would be an issue

2025-01-16 14:55 UTC, colin-morpho commented on certora/specs/ERC20.spec
> +    require holderBalanceBefore <= holderVotingPowerBefore;
Fixed https://github.com/morpho-org/morpho-token/pull/105/commits/f121755090c5ddeb8ec4545d61a6c3569519cc22.

2025-01-16 15:39 UTC, colin-morpho commented on certora/specs/RevertsERC20.spec
> +    require delegatee(to) != delegatee(e.msg.sender) => recipientVotingPowerBefore + amount <= totalSupply();
This should be fixed by https://github.com/morpho-org/morpho-token/pull/105/commits/fdbcc9753bb268a2ed70029676f121b41dd7ce06.

2025-01-16 15:39 UTC, colin-morpho commented on certora/specs/RevertsERC20.spec
> +    // Safe require that follows from sumOfTwoDelegatedVPLTEqTotalVP() and totalSupplyIsSumOfVirtualVotingPower() and rule updatedDelegatedVPLTEqTotalSupply
This should be fixed by https://github.com/morpho-org/morpho-token/pull/105/commits/fdbcc9753bb268a2ed70029676f121b41dd7ce06.

2025-01-16 15:39 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    // Safe require as implementation woud revert.
I changed the require in https://github.com/morpho-org/morpho-token/pull/105/commits/fdbcc9753bb268a2ed70029676f121b41dd7ce06..

2025-01-16 15:52 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
Yes, I do see your point.

2025-01-16 16:07 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    // Safe rquire as zero address can't initiate transactions.
Done in https://github.com/morpho-org/morpho-token/pull/105/commits/389f418fab19f1a688943caf7c5fc2971330637e.

2025-01-16 16:08 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
What do you think about this approach, https://github.com/morpho-org/morpho-token/pull/105/commits/389f418fab19f1a688943caf7c5fc2971330637e.

2025-01-16 16:12 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    // Safe require as implementation woud revert.
The commit linked does not change this part of the code right ?

2025-01-16 16:30 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
It's still unsound unfortunately, because the function could revert sometimes, and it would hide the cases where the invariant does not hold. As a more general example, if the function you are calling reverts when the property you are trying to verify doesn't hold (but doesn't revert otherwise), then you will be able to make this rule pass but it will not be a proof that the property holds.

A concrete example:
```solidity
function g(uint256 x) { require(x < 41); }

rule varIsSmallerThan42 () {
   g@withrevert(storageVar);
   satisfy !lastReverted;
   require !lastReverted;

   assert storageVar < 42;
}
```
This rule will pass (satisfied with `storageVar = 0` for example, and then the assert is just proving `x < 41 => x < 42`), but it does not mean that storageVar is always less than 42

2025-01-16 16:32 UTC, QGarchery commented on certora/specs/RevertsERC20.spec
> +    require delegatee(to) != delegatee(e.msg.sender) => recipientVotingPowerBefore + amount <= totalSupply();
But now it's directly the rule `updatedDelegatedVPLTEqTotalSupply` that should give this property. It has the same premisses as the the rule's `require`s and is has the same conclusion as the rule's `assert`

2025-01-16 16:40 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    // Safe require as implementation woud revert.
The new code still mentions "safe require because XXX implementation would revert", but this rule is not tied to any particular function called. Indeed this will be used as an invariant. 
Those require statements are "safe" because then you would add them as premises when you use use that property. This is the same as in my message above, by doing `require A => B => C`. This would be similar as doing `requireInvariant inv()` if `inv` is the invariant `A => B => C`. You wouldn't say that, in such an invariant, `A` or `B` is a safe premise because of a particular implementation

2025-01-16 16:44 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
Note also that removing the `@withrevert` would also not be sound.
So the rule
```solidity
rule varIsSmallerThan42 () {
   g@withrevert(storageVar);

   assert storageVar < 42;
}
```
would go through, but it's obviously unsound to use it as an invariant (meaning that later you `require storageVar < 42`)

2025-01-16 22:13 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    if (!lastReverted) {
Fixed in https://github.com/morpho-org/morpho-token/pull/105/commits/376c4fded4eafc0b423eba85e085e5cf8583980e.

2025-01-20 15:24 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    // Safe require as implementation woud revert.
Your last message is clearer. I think this now handled in https://github.com/morpho-org/morpho-token/pull/105/commits/06b6407b16f39bb7b8e45ba12cf0d3f8b2bb2e21.

2025-02-03 14:26 UTC, QGarchery requested changes
I noticed other changes that we could make but let's tackle the points below first

2025-02-03 14:26 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    assert delegatedVotingPower(to) + amount <=  totalSupply();
In the rules below, for example in `transferRevertConditions`, the formula written is `recipientVotingPowerBefore + amount <= totalSupply()`. But this is not the same as what's proven here because `recipientVotingPowerBefore == delegatedVotingPower(delegatee(to))` and not `recipientVotingPowerBefore == delegatedVotingPower(to)`

2025-02-03 14:26 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    assert delegatedVotingPower(to) + amount <=  totalSupply();
I realize that there is a flaw in the reasoning of this rule: the assertion should only mention variables before the state change (here it's the `delegate@withrevert` call). This is a flaw because given the previous assert (`delegatee(e.msg.sender) == e.msg.sender`), we could require this and it would say that essentially every account always delegates to himself

2025-02-03 17:20 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    assert delegatedVotingPower(to) + amount <=  totalSupply();
But in line 240 we have `delegatee(msg.sender) == msg.sender` don't we?

2025-02-03 17:33 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    assert delegatedVotingPower(to) + amount <=  totalSupply();
Does the change in https://github.com/morpho-org/morpho-token/pull/105/commits/3fb5d42be3cc7e6e8e9de8d94cab4ce2f32fd922 fixes both comments?

2025-02-04 13:11 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    assert delegatedVotingPower(to) + amount <=  totalSupply();
The rest of the fixes is done in https://github.com/morpho-org/morpho-token/pull/105/commits/3fb5d42be3cc7e6e8e9de8d94cab4ce2f32fd922. For the record, the soundness issue stems from the fact that we prove properties **only** on the state **preceding** the call to `delegate`. Also, readability is improved by removing the environment from the parameters of the rule, instead we choose an arbitrary environment `e` such that the message sender equals the user who makes the transfer but different from the one where the rule might be required. The latter change is merely cosmetic but should clarify the relation to the environment.

2025-02-04 15:31 UTC, QGarchery reviewed
Much cleaner :sparkles:

2025-02-04 15:31 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    require e.msg.sender == from;
Let's put this below when it is first used: just before calling `delegate@withrevert`. We could also explain why those require-statements are safe: it's because tjhey are part of a ghost execution

2025-02-04 15:31 UTC, QGarchery commented on certora/specs/Delegation.spec
Let's remove this assert, as it is distracting (because it doesn't use variables that are defined before the ghost execution), and it's not useful

2025-02-04 15:31 UTC, QGarchery commented on certora/specs/Delegation.spec
>      assert(!lastReverted);
```suggestion
    assert !lastReverted;
```
(optional)

2025-02-04 15:31 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    require delegatee(to) != delegatee(from);
Let's explain why those require-statements are safe: this could be at the top of the rule, stating what formula we are trying to prove, that is `from != 0 => delegatee(to) != delegatee(from) => delegatedVotingPower(delegateee(to)) + balanceOf(from) <= totalSupply()`

2025-02-04 15:31 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    // This invariant can't be required as it's using a parameterized variable.
```suggestion
```
or we could add it to other places where it is used (searching for delegatedLTEqDelegateeVP in the comments)

2025-02-04 15:48 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    // This invariant can't be required as it's using a parameterized variable.
Done in https://github.com/morpho-org/morpho-token/pull/105/commits/619435e704053ec6d15c49486778edeca12e6804.

2025-02-04 15:48 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    require delegatee(to) != delegatee(from);
What do you think of the comment added in https://github.com/morpho-org/morpho-token/pull/105/commits/619435e704053ec6d15c49486778edeca12e6804.

2025-02-04 15:49 UTC, colin-morpho commented on certora/specs/Delegation.spec
>      assert(!lastReverted);
Done in https://github.com/morpho-org/morpho-token/pull/105/commits/619435e704053ec6d15c49486778edeca12e6804.

2025-02-04 15:49 UTC, colin-morpho commented on certora/specs/Delegation.spec
Done in https://github.com/morpho-org/morpho-token/pull/105/commits/619435e704053ec6d15c49486778edeca12e6804.

2025-02-04 16:59 UTC, QGarchery approved these changes, later dismissed
Nice

2025-02-04 16:59 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    env e;
(optional) to move it just before the require on e.msg.sender and e.msg.value

2025-02-04 17:00 UTC, QGarchery commented on certora/specs/Delegation.spec
> +    env e;
(I'm talking about just the definition of `e`)

2025-02-04 17:03 UTC, colin-morpho commented on certora/specs/Delegation.spec
> +    env e;
Done in https://github.com/morpho-org/morpho-token/pull/105/commits/4de56d884b96678b2861e89165f524bfe80ac698.

2025-02-04 19:18 UTC, QGarchery approved these changes, later dismissed

2025-02-11 12:54 UTC, MathisGD commented on certora/specs/Delegation.spec
> +    // This require avoids an impossible revert as zeroVirtualVotingPower operations comme from munging.
```suggestion
    // This require avoids an impossible revert as zeroVirtualVotingPower operations come from munging.
```

2025-02-11 12:55 UTC, MathisGD commented on certora/specs/Delegation.spec
> +rule updatedDelegatedVPLTEqTotalSupply(address from, address to) {
```suggestion
rule updatedDelegatedVPLTEqTotalSupply(env e, address from, address to) {
```

2025-02-11 12:56 UTC, MathisGD commented on certora/specs/Delegation.spec
> +
```suggestion
    delegate(e, from);
```

2025-02-11 12:57 UTC, MathisGD commented on certora/specs/Delegation.spec
> +    // Safe require-statements that introduce the premises of the goal formula, from != 0 => delegatee(to) != delegatee(from) => delegatedVotingPower(delegateee(to)) + balanceOf(from) <= totalSupply(
```suggestion
    // Safe require-statements that introduce the premises of the goal formula, from != 0 => delegatee(to) != delegatee(from) => delegatedVotingPower(delegatee(to)) + balanceOf(from) <= totalSupply().
```

2025-02-11 13:11 UTC, MathisGD commented on certora/specs/Delegation.spec
> +rule updatedDelegatedVPLTEqTotalSupply(address from, address to) {
actually I don't understand this rule: we don't query anything after the delegate? and where is that transfer?

2025-02-11 13:13 UTC, MathisGD commented on certora/specs/MintBurnEthereum.spec
>      } else {
could we avoid this pattern? (and have a rule for checking reverts, and one rule for checking the non revert case's effects)

2025-02-11 13:55 UTC, QGarchery commented on certora/specs/Delegation.spec
> +rule updatedDelegatedVPLTEqTotalSupply(address from, address to) {
In this case, let's not do this change. This is because the environment `e` is ghost, and we want to use this rule as an invariant later. An invariant would not have this environment parameter, so it would make it confusing

2025-02-11 14:03 UTC, QGarchery commented on certora/specs/MintBurnEthereum.spec
>      } else {
I think we are still following OZ's specs (and actually getting closer to it in this PR)

2025-02-11 14:11 UTC, colin-morpho commented on certora/specs/MintBurnEthereum.spec
>      } else {
Yes, we did mention the idea of a more generic framework on ERC20 at some point but we didn't find a clever way to make this happen to decided to continue this route.

2025-02-13 13:38 UTC, QGarchery commented on certora/specs/Delegation.spec
> +rule updatedDelegatedVPLTEqTotalSupply(address from, address to) {
> I think we should remove the mention to transfer, as it's not needed for this rule.

It would be fixed in #108

2025-02-13 13:38 UTC, QGarchery approved these changes, later dismissed

2025-02-14 08:42 UTC, QGarchery commented on certora/specs/Delegation.spec
> +rule updatedDelegatedVPLTEqTotalSupply(address from, address to) {
will be rendered moot by #108 anyway

2025-02-17 11:20 UTC, QGarchery approved these changes

2026-07-31 18:54 UTC, MathisGD approved these changes

2026-07-31 18:54 UTC, merged